services:
  - type: web
    name: tetris-relay
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    rootDir: server
    envVars:
      - key: PORT
        value: 10000
